### ISSUE TITLE
split up scripting responsibilities

### ISSUE THREAD

**Issue by sheilasaia** [eam-group/2024-esmc-plet#6]
Split up according to script for now (can always revise this):

~~- [ ] parse mmrv output~~
~~- [ ] get prism data (brian)~~
~~- [ ] save cdl data to data folder (brian)~~, see #11
~~- [ ] save nlcd data to data folder (brian)~~, see #10
- [x] function development (sheila)
- [x] list of inputs (sheila)
- [x] save lookup tables (sheila)
- [x] calculate baseline and practice change impacts for dummy file (sheila)
- [x] geojson for testing (brian and sheila)
- [x] flask framework (brian)
- [x] docker stuff (brian)
- [x] check that plet module values match with stepl values (sheila and maddie)
- [x] look into getting nass animal counts data (brian look into), see #21 
- [x] look into getting soils data (brian look into), see #9 
- [x] tiger data processing functions and appending data to gdf
- [x] nhdplus data processing functions and appending data to gdf
- [x] ecoregions data processing functions and appending data to gdf (sheila)
- [x] update usle and precip lookups (sheila)
- [x] nass animal counts processing functions (current ones need to be iterated for multiple fips) (sheila)
- [x] nass for loop, merged file, and function to select year that's closest (sheila)
- [x] down-scale nass to cropland/pastureland (brian/sheila)
- [x] code to get hsg tif (brian/sheila)
- [x] write standard tests (all), see #18
